--------------------------------------------------------
--  File created - Wednesday-January-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DISTRIBUTER
--------------------------------------------------------

  CREATE TABLE "C##IGOR"."DISTRIBUTER" 
   (	"IDDIST" NUMBER(*,0), 
	"NAZIVDIST" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ISPORUCUJE
--------------------------------------------------------

  CREATE TABLE "C##IGOR"."ISPORUCUJE" 
   (	"POTPISANPUD_DISTRIBUTER_IDDIST" NUMBER(*,0), 
	"POTPISANPUD_PRODUGOVOR_IDUGO" NUMBER(*,0), 
	"OBUHVATAPROIZ_IDUGO" NUMBER(*,0), 
	"OBUHVATAPROIZ_IDPROIZ" NUMBER(*,0), 
	"PRODAVNICA_IDPROD" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MENADZER
--------------------------------------------------------

  CREATE TABLE "C##IGOR"."MENADZER" 
   (	"IDZAP" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NABUGOVOR
--------------------------------------------------------

  CREATE TABLE "C##IGOR"."NABUGOVOR" 
   (	"IDUGO" NUMBER(*,0), 
	"DISTRIBUTER_IDDIST" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OBUHVATAPROIZ
--------------------------------------------------------

  CREATE TABLE "C##IGOR"."OBUHVATAPROIZ" 
   (	"KOLICINA" NUMBER(*,0), 
	"PRODUGOVOR_IDUGO" NUMBER(*,0), 
	"PROIZVOD_IDPROIZ" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OBUHVATASIR
--------------------------------------------------------

  CREATE TABLE "C##IGOR"."OBUHVATASIR" 
   (	"NABUGOVOR_IDUGO" NUMBER(*,0), 
	"SIROVINA_IDSIR" NUMBER(*,0), 
	"KOLICINA" FLOAT(126), 
	"JEDINICA" VARCHAR2(8 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PEKAR
--------------------------------------------------------

  CREATE TABLE "C##IGOR"."PEKAR" 
   (	"IDZAP" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POTPISANPUD
--------------------------------------------------------

  CREATE TABLE "C##IGOR"."POTPISANPUD" 
   (	"DISTRIBUTER_IDDIST" NUMBER(*,0), 
	"PRODUGOVOR_IDUGO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRAVI
--------------------------------------------------------

  CREATE TABLE "C##IGOR"."PRAVI" 
   (	"PEKAR_IDZAP" NUMBER(*,0), 
	"PROIZVOD_IDPROIZ" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODAVNICA
--------------------------------------------------------

  CREATE TABLE "C##IGOR"."PRODAVNICA" 
   (	"IDPROD" NUMBER(*,0), 
	"NAZIVPROD" VARCHAR2(32 CHAR), 
	"ADRESAPROD" VARCHAR2(128 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUGOVOR
--------------------------------------------------------

  CREATE TABLE "C##IGOR"."PRODUGOVOR" 
   (	"IDUGO" NUMBER(*,0), 
	"PRODAVNICA_IDPROD" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROIZVOD
--------------------------------------------------------

  CREATE TABLE "C##IGOR"."PROIZVOD" 
   (	"IDPROIZ" NUMBER(*,0), 
	"MASAPROIZ" FLOAT(126), 
	"NAZIVPROIZ" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SASTAV
--------------------------------------------------------

  CREATE TABLE "C##IGOR"."SASTAV" 
   (	"PROIZVOD_IDPROIZ" NUMBER(*,0), 
	"SIROVINA_IDSIR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIROVINA
--------------------------------------------------------

  CREATE TABLE "C##IGOR"."SIROVINA" 
   (	"IDSIR" NUMBER(*,0), 
	"NAZIVSIR" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UGOVOR
--------------------------------------------------------

  CREATE TABLE "C##IGOR"."UGOVOR" 
   (	"IDUGO" NUMBER(*,0), 
	"TIPUGO" VARCHAR2(16 CHAR), 
	"MENADZER_IDZAP" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZAPOSLENI
--------------------------------------------------------

  CREATE TABLE "C##IGOR"."ZAPOSLENI" 
   (	"IDZAP" NUMBER(*,0), 
	"IMEZAP" VARCHAR2(32 CHAR), 
	"TIPZAP" VARCHAR2(16 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##IGOR.DISTRIBUTER
SET DEFINE OFF;
Insert into C##IGOR.DISTRIBUTER (IDDIST,NAZIVDIST) values (1,'pekardist');
Insert into C##IGOR.DISTRIBUTER (IDDIST,NAZIVDIST) values (2,'dm');
Insert into C##IGOR.DISTRIBUTER (IDDIST,NAZIVDIST) values (3,'ATACO');
REM INSERTING into C##IGOR.ISPORUCUJE
SET DEFINE OFF;
Insert into C##IGOR.ISPORUCUJE (POTPISANPUD_DISTRIBUTER_IDDIST,POTPISANPUD_PRODUGOVOR_IDUGO,OBUHVATAPROIZ_IDUGO,OBUHVATAPROIZ_IDPROIZ,PRODAVNICA_IDPROD) values (1,2,2,2,1);
Insert into C##IGOR.ISPORUCUJE (POTPISANPUD_DISTRIBUTER_IDDIST,POTPISANPUD_PRODUGOVOR_IDUGO,OBUHVATAPROIZ_IDUGO,OBUHVATAPROIZ_IDPROIZ,PRODAVNICA_IDPROD) values (1,3,3,1,2);
Insert into C##IGOR.ISPORUCUJE (POTPISANPUD_DISTRIBUTER_IDDIST,POTPISANPUD_PRODUGOVOR_IDUGO,OBUHVATAPROIZ_IDUGO,OBUHVATAPROIZ_IDPROIZ,PRODAVNICA_IDPROD) values (2,4,4,2,3);
Insert into C##IGOR.ISPORUCUJE (POTPISANPUD_DISTRIBUTER_IDDIST,POTPISANPUD_PRODUGOVOR_IDUGO,OBUHVATAPROIZ_IDUGO,OBUHVATAPROIZ_IDPROIZ,PRODAVNICA_IDPROD) values (2,5,5,1,4);
Insert into C##IGOR.ISPORUCUJE (POTPISANPUD_DISTRIBUTER_IDDIST,POTPISANPUD_PRODUGOVOR_IDUGO,OBUHVATAPROIZ_IDUGO,OBUHVATAPROIZ_IDPROIZ,PRODAVNICA_IDPROD) values (2,3,3,4,2);
Insert into C##IGOR.ISPORUCUJE (POTPISANPUD_DISTRIBUTER_IDDIST,POTPISANPUD_PRODUGOVOR_IDUGO,OBUHVATAPROIZ_IDUGO,OBUHVATAPROIZ_IDPROIZ,PRODAVNICA_IDPROD) values (1,2,2,3,1);
REM INSERTING into C##IGOR.MENADZER
SET DEFINE OFF;
Insert into C##IGOR.MENADZER (IDZAP) values (1);
Insert into C##IGOR.MENADZER (IDZAP) values (4);
REM INSERTING into C##IGOR.NABUGOVOR
SET DEFINE OFF;
Insert into C##IGOR.NABUGOVOR (IDUGO,DISTRIBUTER_IDDIST) values (1,1);
Insert into C##IGOR.NABUGOVOR (IDUGO,DISTRIBUTER_IDDIST) values (6,3);
Insert into C##IGOR.NABUGOVOR (IDUGO,DISTRIBUTER_IDDIST) values (7,1);
REM INSERTING into C##IGOR.OBUHVATAPROIZ
SET DEFINE OFF;
Insert into C##IGOR.OBUHVATAPROIZ (KOLICINA,PRODUGOVOR_IDUGO,PROIZVOD_IDPROIZ) values (5,3,4);
Insert into C##IGOR.OBUHVATAPROIZ (KOLICINA,PRODUGOVOR_IDUGO,PROIZVOD_IDPROIZ) values (20,3,1);
Insert into C##IGOR.OBUHVATAPROIZ (KOLICINA,PRODUGOVOR_IDUGO,PROIZVOD_IDPROIZ) values (20,2,2);
Insert into C##IGOR.OBUHVATAPROIZ (KOLICINA,PRODUGOVOR_IDUGO,PROIZVOD_IDPROIZ) values (100,2,3);
Insert into C##IGOR.OBUHVATAPROIZ (KOLICINA,PRODUGOVOR_IDUGO,PROIZVOD_IDPROIZ) values (50,4,2);
Insert into C##IGOR.OBUHVATAPROIZ (KOLICINA,PRODUGOVOR_IDUGO,PROIZVOD_IDPROIZ) values (300,5,1);
REM INSERTING into C##IGOR.OBUHVATASIR
SET DEFINE OFF;
Insert into C##IGOR.OBUHVATASIR (NABUGOVOR_IDUGO,SIROVINA_IDSIR,KOLICINA,JEDINICA) values (1,1,350,'kg');
Insert into C##IGOR.OBUHVATASIR (NABUGOVOR_IDUGO,SIROVINA_IDSIR,KOLICINA,JEDINICA) values (6,2,10,'kg');
Insert into C##IGOR.OBUHVATASIR (NABUGOVOR_IDUGO,SIROVINA_IDSIR,KOLICINA,JEDINICA) values (7,3,2000,'g');
Insert into C##IGOR.OBUHVATASIR (NABUGOVOR_IDUGO,SIROVINA_IDSIR,KOLICINA,JEDINICA) values (1,4,5,'kg');
Insert into C##IGOR.OBUHVATASIR (NABUGOVOR_IDUGO,SIROVINA_IDSIR,KOLICINA,JEDINICA) values (1,5,750,'g');
Insert into C##IGOR.OBUHVATASIR (NABUGOVOR_IDUGO,SIROVINA_IDSIR,KOLICINA,JEDINICA) values (6,1,165.4,'kg');
Insert into C##IGOR.OBUHVATASIR (NABUGOVOR_IDUGO,SIROVINA_IDSIR,KOLICINA,JEDINICA) values (7,4,1.25,'kg');
REM INSERTING into C##IGOR.PEKAR
SET DEFINE OFF;
Insert into C##IGOR.PEKAR (IDZAP) values (2);
Insert into C##IGOR.PEKAR (IDZAP) values (3);
REM INSERTING into C##IGOR.POTPISANPUD
SET DEFINE OFF;
Insert into C##IGOR.POTPISANPUD (DISTRIBUTER_IDDIST,PRODUGOVOR_IDUGO) values (1,2);
Insert into C##IGOR.POTPISANPUD (DISTRIBUTER_IDDIST,PRODUGOVOR_IDUGO) values (1,3);
Insert into C##IGOR.POTPISANPUD (DISTRIBUTER_IDDIST,PRODUGOVOR_IDUGO) values (2,3);
Insert into C##IGOR.POTPISANPUD (DISTRIBUTER_IDDIST,PRODUGOVOR_IDUGO) values (2,4);
Insert into C##IGOR.POTPISANPUD (DISTRIBUTER_IDDIST,PRODUGOVOR_IDUGO) values (2,5);
REM INSERTING into C##IGOR.PRAVI
SET DEFINE OFF;
Insert into C##IGOR.PRAVI (PEKAR_IDZAP,PROIZVOD_IDPROIZ) values (2,1);
Insert into C##IGOR.PRAVI (PEKAR_IDZAP,PROIZVOD_IDPROIZ) values (2,4);
Insert into C##IGOR.PRAVI (PEKAR_IDZAP,PROIZVOD_IDPROIZ) values (3,2);
Insert into C##IGOR.PRAVI (PEKAR_IDZAP,PROIZVOD_IDPROIZ) values (3,3);
Insert into C##IGOR.PRAVI (PEKAR_IDZAP,PROIZVOD_IDPROIZ) values (3,4);
REM INSERTING into C##IGOR.PRODAVNICA
SET DEFINE OFF;
Insert into C##IGOR.PRODAVNICA (IDPROD,NAZIVPROD,ADRESAPROD) values (1,'Mimoza','VK bb');
Insert into C##IGOR.PRODAVNICA (IDPROD,NAZIVPROD,ADRESAPROD) values (2,'Jokic','K 30');
Insert into C##IGOR.PRODAVNICA (IDPROD,NAZIVPROD,ADRESAPROD) values (3,'Malo Polje','kar nn');
Insert into C##IGOR.PRODAVNICA (IDPROD,NAZIVPROD,ADRESAPROD) values (4,'Z makreti','IB 10');
REM INSERTING into C##IGOR.PRODUGOVOR
SET DEFINE OFF;
Insert into C##IGOR.PRODUGOVOR (IDUGO,PRODAVNICA_IDPROD) values (2,1);
Insert into C##IGOR.PRODUGOVOR (IDUGO,PRODAVNICA_IDPROD) values (3,2);
Insert into C##IGOR.PRODUGOVOR (IDUGO,PRODAVNICA_IDPROD) values (4,3);
Insert into C##IGOR.PRODUGOVOR (IDUGO,PRODAVNICA_IDPROD) values (5,4);
REM INSERTING into C##IGOR.PROIZVOD
SET DEFINE OFF;
Insert into C##IGOR.PROIZVOD (IDPROIZ,MASAPROIZ,NAZIVPROIZ) values (1,0.6,'hljeb');
Insert into C##IGOR.PROIZVOD (IDPROIZ,MASAPROIZ,NAZIVPROIZ) values (2,0.08,'kifla');
Insert into C##IGOR.PROIZVOD (IDPROIZ,MASAPROIZ,NAZIVPROIZ) values (3,null,'slatko pecivo');
Insert into C##IGOR.PROIZVOD (IDPROIZ,MASAPROIZ,NAZIVPROIZ) values (4,0.35,'kore za pitu');
REM INSERTING into C##IGOR.SASTAV
SET DEFINE OFF;
Insert into C##IGOR.SASTAV (PROIZVOD_IDPROIZ,SIROVINA_IDSIR) values (1,1);
Insert into C##IGOR.SASTAV (PROIZVOD_IDPROIZ,SIROVINA_IDSIR) values (1,3);
Insert into C##IGOR.SASTAV (PROIZVOD_IDPROIZ,SIROVINA_IDSIR) values (1,5);
Insert into C##IGOR.SASTAV (PROIZVOD_IDPROIZ,SIROVINA_IDSIR) values (1,6);
Insert into C##IGOR.SASTAV (PROIZVOD_IDPROIZ,SIROVINA_IDSIR) values (2,1);
Insert into C##IGOR.SASTAV (PROIZVOD_IDPROIZ,SIROVINA_IDSIR) values (2,2);
Insert into C##IGOR.SASTAV (PROIZVOD_IDPROIZ,SIROVINA_IDSIR) values (2,4);
Insert into C##IGOR.SASTAV (PROIZVOD_IDPROIZ,SIROVINA_IDSIR) values (3,1);
Insert into C##IGOR.SASTAV (PROIZVOD_IDPROIZ,SIROVINA_IDSIR) values (3,2);
Insert into C##IGOR.SASTAV (PROIZVOD_IDPROIZ,SIROVINA_IDSIR) values (3,4);
Insert into C##IGOR.SASTAV (PROIZVOD_IDPROIZ,SIROVINA_IDSIR) values (4,1);
REM INSERTING into C##IGOR.SIROVINA
SET DEFINE OFF;
Insert into C##IGOR.SIROVINA (IDSIR,NAZIVSIR) values (1,'brasno');
Insert into C##IGOR.SIROVINA (IDSIR,NAZIVSIR) values (2,'secer');
Insert into C##IGOR.SIROVINA (IDSIR,NAZIVSIR) values (3,'so');
Insert into C##IGOR.SIROVINA (IDSIR,NAZIVSIR) values (4,'maslac');
Insert into C##IGOR.SIROVINA (IDSIR,NAZIVSIR) values (5,'prasak za pecivo');
Insert into C##IGOR.SIROVINA (IDSIR,NAZIVSIR) values (6,'kvasac');
REM INSERTING into C##IGOR.UGOVOR
SET DEFINE OFF;
Insert into C##IGOR.UGOVOR (IDUGO,TIPUGO,MENADZER_IDZAP) values (1,'NabUgovor',1);
Insert into C##IGOR.UGOVOR (IDUGO,TIPUGO,MENADZER_IDZAP) values (2,'ProdUgovor',1);
Insert into C##IGOR.UGOVOR (IDUGO,TIPUGO,MENADZER_IDZAP) values (3,'ProdUgovor',1);
Insert into C##IGOR.UGOVOR (IDUGO,TIPUGO,MENADZER_IDZAP) values (4,'ProdUgovor',1);
Insert into C##IGOR.UGOVOR (IDUGO,TIPUGO,MENADZER_IDZAP) values (5,'ProdUgovor',1);
Insert into C##IGOR.UGOVOR (IDUGO,TIPUGO,MENADZER_IDZAP) values (6,'NabUgovor',1);
Insert into C##IGOR.UGOVOR (IDUGO,TIPUGO,MENADZER_IDZAP) values (7,'NabUgovor',1);
REM INSERTING into C##IGOR.ZAPOSLENI
SET DEFINE OFF;
Insert into C##IGOR.ZAPOSLENI (IDZAP,IMEZAP,TIPZAP) values (1,'Igor S.','Menadzer');
Insert into C##IGOR.ZAPOSLENI (IDZAP,IMEZAP,TIPZAP) values (2,'Rados','Pekar');
Insert into C##IGOR.ZAPOSLENI (IDZAP,IMEZAP,TIPZAP) values (3,'Boza Arsa','Pekar');
Insert into C##IGOR.ZAPOSLENI (IDZAP,IMEZAP,TIPZAP) values (4,'Andrej Hodza','Menadzer');
--------------------------------------------------------
--  DDL for Index DISTRIBUTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##IGOR"."DISTRIBUTER_PK" ON "C##IGOR"."DISTRIBUTER" ("IDDIST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ISPORUCUJE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##IGOR"."ISPORUCUJE_PK" ON "C##IGOR"."ISPORUCUJE" ("POTPISANPUD_DISTRIBUTER_IDDIST", "POTPISANPUD_PRODUGOVOR_IDUGO", "OBUHVATAPROIZ_IDUGO", "OBUHVATAPROIZ_IDPROIZ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MENADZER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##IGOR"."MENADZER_PK" ON "C##IGOR"."MENADZER" ("IDZAP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NABUGOVOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##IGOR"."NABUGOVOR_PK" ON "C##IGOR"."NABUGOVOR" ("IDUGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OBUHVATAPROIZ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##IGOR"."OBUHVATAPROIZ_PK" ON "C##IGOR"."OBUHVATAPROIZ" ("PRODUGOVOR_IDUGO", "PROIZVOD_IDPROIZ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OBUHVATASIR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##IGOR"."OBUHVATASIR_PK" ON "C##IGOR"."OBUHVATASIR" ("NABUGOVOR_IDUGO", "SIROVINA_IDSIR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PEKAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##IGOR"."PEKAR_PK" ON "C##IGOR"."PEKAR" ("IDZAP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index POTPISANPUD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##IGOR"."POTPISANPUD_PK" ON "C##IGOR"."POTPISANPUD" ("DISTRIBUTER_IDDIST", "PRODUGOVOR_IDUGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRAVI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##IGOR"."PRAVI_PK" ON "C##IGOR"."PRAVI" ("PEKAR_IDZAP", "PROIZVOD_IDPROIZ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODAVNICA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##IGOR"."PRODAVNICA_PK" ON "C##IGOR"."PRODAVNICA" ("IDPROD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUGOVOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##IGOR"."PRODUGOVOR_PK" ON "C##IGOR"."PRODUGOVOR" ("IDUGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROIZVOD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##IGOR"."PROIZVOD_PK" ON "C##IGOR"."PROIZVOD" ("IDPROIZ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SASTAV_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##IGOR"."SASTAV_PK" ON "C##IGOR"."SASTAV" ("PROIZVOD_IDPROIZ", "SIROVINA_IDSIR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIROVINA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##IGOR"."SIROVINA_PK" ON "C##IGOR"."SIROVINA" ("IDSIR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UGOVOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##IGOR"."UGOVOR_PK" ON "C##IGOR"."UGOVOR" ("IDUGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ZAPOSLENI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##IGOR"."ZAPOSLENI_PK" ON "C##IGOR"."ZAPOSLENI" ("IDZAP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_1_NABUGOVOR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##IGOR"."ARC_FKARC_1_NABUGOVOR" BEFORE
    INSERT OR UPDATE OF idugo ON nabugovor
    FOR EACH ROW
DECLARE
    d VARCHAR2(16 CHAR);
BEGIN
    SELECT
        a.tipugo
    INTO d
    FROM
        ugovor a
    WHERE
        a.idugo = :new.idugo;

    IF ( d IS NULL OR d <> 'NabUgovor' ) THEN
        raise_application_error(-20223,
                               'FK NabUgovor_Ugovor_FK in Table NabUgovor violates Arc constraint on Table Ugovor - discriminator column tipUgo doesn''t have value ''NabUgovor''');
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;

/
ALTER TRIGGER "C##IGOR"."ARC_FKARC_1_NABUGOVOR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_1_PRODUGOVOR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##IGOR"."ARC_FKARC_1_PRODUGOVOR" BEFORE
    INSERT OR UPDATE OF idugo ON produgovor
    FOR EACH ROW
DECLARE
    d VARCHAR2(16 CHAR);
BEGIN
    SELECT
        a.tipugo
    INTO d
    FROM
        ugovor a
    WHERE
        a.idugo = :new.idugo;

    IF ( d IS NULL OR d <> 'ProdUgovor' ) THEN
        raise_application_error(-20223,
                               'FK ProdUgovor_Ugovor_FK in Table ProdUgovor violates Arc constraint on Table Ugovor - discriminator column tipUgo doesn''t have value ''ProdUgovor''');
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;

/
ALTER TRIGGER "C##IGOR"."ARC_FKARC_1_PRODUGOVOR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_2_MENADZER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##IGOR"."ARC_FKARC_2_MENADZER" BEFORE
    INSERT OR UPDATE OF idzap ON menadzer
    FOR EACH ROW
DECLARE
    d VARCHAR2(16 CHAR);
BEGIN
    SELECT
        a.tipzap
    INTO d
    FROM
        zaposleni a
    WHERE
        a.idzap = :new.idzap;

    IF ( d IS NULL OR d <> 'Menadzer' ) THEN
        raise_application_error(-20223,
                               'FK Menadzer_Zaposleni_FK in Table Menadzer violates Arc constraint on Table Zaposleni - discriminator column tipZap doesn''t have value ''Menadzer''');
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;

/
ALTER TRIGGER "C##IGOR"."ARC_FKARC_2_MENADZER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_2_PEKAR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##IGOR"."ARC_FKARC_2_PEKAR" BEFORE
    INSERT OR UPDATE OF idzap ON pekar
    FOR EACH ROW
DECLARE
    d VARCHAR2(16 CHAR);
BEGIN
    SELECT
        a.tipzap
    INTO d
    FROM
        zaposleni a
    WHERE
        a.idzap = :new.idzap;

    IF ( d IS NULL OR d <> 'Pekar' ) THEN
        raise_application_error(-20223,
                               'FK Pekar_Zaposleni_FK in Table Pekar violates Arc constraint on Table Zaposleni - discriminator column tipZap doesn''t have value ''Pekar''');
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;

/
ALTER TRIGGER "C##IGOR"."ARC_FKARC_2_PEKAR" ENABLE;
--------------------------------------------------------
--  Constraints for Table DISTRIBUTER
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."DISTRIBUTER" MODIFY ("IDDIST" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."DISTRIBUTER" MODIFY ("NAZIVDIST" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."DISTRIBUTER" ADD CONSTRAINT "DISTRIBUTER_PK" PRIMARY KEY ("IDDIST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ISPORUCUJE
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."ISPORUCUJE" MODIFY ("POTPISANPUD_DISTRIBUTER_IDDIST" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."ISPORUCUJE" MODIFY ("POTPISANPUD_PRODUGOVOR_IDUGO" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."ISPORUCUJE" MODIFY ("OBUHVATAPROIZ_IDUGO" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."ISPORUCUJE" MODIFY ("OBUHVATAPROIZ_IDPROIZ" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."ISPORUCUJE" MODIFY ("PRODAVNICA_IDPROD" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."ISPORUCUJE" ADD CONSTRAINT "ISPORUCUJE_PK" PRIMARY KEY ("POTPISANPUD_DISTRIBUTER_IDDIST", "POTPISANPUD_PRODUGOVOR_IDUGO", "OBUHVATAPROIZ_IDUGO", "OBUHVATAPROIZ_IDPROIZ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MENADZER
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."MENADZER" MODIFY ("IDZAP" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."MENADZER" ADD CONSTRAINT "MENADZER_PK" PRIMARY KEY ("IDZAP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NABUGOVOR
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."NABUGOVOR" MODIFY ("IDUGO" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."NABUGOVOR" MODIFY ("DISTRIBUTER_IDDIST" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."NABUGOVOR" ADD CONSTRAINT "NABUGOVOR_PK" PRIMARY KEY ("IDUGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OBUHVATAPROIZ
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."OBUHVATAPROIZ" MODIFY ("PRODUGOVOR_IDUGO" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."OBUHVATAPROIZ" MODIFY ("PROIZVOD_IDPROIZ" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."OBUHVATAPROIZ" ADD CONSTRAINT "OBUHVATAPROIZ_PK" PRIMARY KEY ("PRODUGOVOR_IDUGO", "PROIZVOD_IDPROIZ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OBUHVATASIR
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."OBUHVATASIR" MODIFY ("NABUGOVOR_IDUGO" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."OBUHVATASIR" MODIFY ("SIROVINA_IDSIR" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."OBUHVATASIR" ADD CONSTRAINT "OBUHVATASIR_PK" PRIMARY KEY ("NABUGOVOR_IDUGO", "SIROVINA_IDSIR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PEKAR
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."PEKAR" MODIFY ("IDZAP" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."PEKAR" ADD CONSTRAINT "PEKAR_PK" PRIMARY KEY ("IDZAP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POTPISANPUD
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."POTPISANPUD" MODIFY ("DISTRIBUTER_IDDIST" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."POTPISANPUD" MODIFY ("PRODUGOVOR_IDUGO" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."POTPISANPUD" ADD CONSTRAINT "POTPISANPUD_PK" PRIMARY KEY ("DISTRIBUTER_IDDIST", "PRODUGOVOR_IDUGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRAVI
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."PRAVI" MODIFY ("PEKAR_IDZAP" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."PRAVI" MODIFY ("PROIZVOD_IDPROIZ" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."PRAVI" ADD CONSTRAINT "PRAVI_PK" PRIMARY KEY ("PEKAR_IDZAP", "PROIZVOD_IDPROIZ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODAVNICA
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."PRODAVNICA" MODIFY ("IDPROD" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."PRODAVNICA" MODIFY ("NAZIVPROD" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."PRODAVNICA" ADD CONSTRAINT "PRODAVNICA_PK" PRIMARY KEY ("IDPROD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUGOVOR
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."PRODUGOVOR" MODIFY ("IDUGO" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."PRODUGOVOR" MODIFY ("PRODAVNICA_IDPROD" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."PRODUGOVOR" ADD CONSTRAINT "PRODUGOVOR_PK" PRIMARY KEY ("IDUGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROIZVOD
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."PROIZVOD" MODIFY ("IDPROIZ" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."PROIZVOD" MODIFY ("NAZIVPROIZ" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."PROIZVOD" ADD CONSTRAINT "PROIZVOD_PK" PRIMARY KEY ("IDPROIZ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SASTAV
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."SASTAV" MODIFY ("PROIZVOD_IDPROIZ" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."SASTAV" MODIFY ("SIROVINA_IDSIR" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."SASTAV" ADD CONSTRAINT "SASTAV_PK" PRIMARY KEY ("PROIZVOD_IDPROIZ", "SIROVINA_IDSIR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SIROVINA
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."SIROVINA" MODIFY ("IDSIR" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."SIROVINA" MODIFY ("NAZIVSIR" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."SIROVINA" ADD CONSTRAINT "SIROVINA_PK" PRIMARY KEY ("IDSIR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UGOVOR
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."UGOVOR" MODIFY ("IDUGO" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."UGOVOR" MODIFY ("TIPUGO" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."UGOVOR" MODIFY ("MENADZER_IDZAP" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."UGOVOR" ADD CONSTRAINT "CH_INH_UGOVOR" CHECK ( tipugo IN ( 'NabUgovor', 'ProdUgovor', 'Ugovor' ) ) ENABLE;
  ALTER TABLE "C##IGOR"."UGOVOR" ADD CONSTRAINT "UGOVOR_PK" PRIMARY KEY ("IDUGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZAPOSLENI
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."ZAPOSLENI" MODIFY ("IDZAP" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."ZAPOSLENI" MODIFY ("IMEZAP" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."ZAPOSLENI" MODIFY ("TIPZAP" NOT NULL ENABLE);
  ALTER TABLE "C##IGOR"."ZAPOSLENI" ADD CONSTRAINT "CH_INH_ZAPOSLENI" CHECK ( tipzap IN ( 'Menadzer', 'Pekar', 'Zaposleni' ) ) ENABLE;
  ALTER TABLE "C##IGOR"."ZAPOSLENI" ADD CONSTRAINT "ZAPOSLENI_PK" PRIMARY KEY ("IDZAP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ISPORUCUJE
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."ISPORUCUJE" ADD CONSTRAINT "ISPORUCUJE_OBUHVATAPROIZ_FK" FOREIGN KEY ("OBUHVATAPROIZ_IDUGO", "OBUHVATAPROIZ_IDPROIZ")
	  REFERENCES "C##IGOR"."OBUHVATAPROIZ" ("PRODUGOVOR_IDUGO", "PROIZVOD_IDPROIZ") ENABLE;
  ALTER TABLE "C##IGOR"."ISPORUCUJE" ADD CONSTRAINT "ISPORUCUJE_POTPISANPUD_FK" FOREIGN KEY ("POTPISANPUD_DISTRIBUTER_IDDIST", "POTPISANPUD_PRODUGOVOR_IDUGO")
	  REFERENCES "C##IGOR"."POTPISANPUD" ("DISTRIBUTER_IDDIST", "PRODUGOVOR_IDUGO") ENABLE;
  ALTER TABLE "C##IGOR"."ISPORUCUJE" ADD CONSTRAINT "ISPORUCUJE_PRODAVNICA_FK" FOREIGN KEY ("PRODAVNICA_IDPROD")
	  REFERENCES "C##IGOR"."PRODAVNICA" ("IDPROD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MENADZER
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."MENADZER" ADD CONSTRAINT "MENADZER_ZAPOSLENI_FK" FOREIGN KEY ("IDZAP")
	  REFERENCES "C##IGOR"."ZAPOSLENI" ("IDZAP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NABUGOVOR
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."NABUGOVOR" ADD CONSTRAINT "NABUGOVOR_DISTRIBUTER_FK" FOREIGN KEY ("DISTRIBUTER_IDDIST")
	  REFERENCES "C##IGOR"."DISTRIBUTER" ("IDDIST") ENABLE;
  ALTER TABLE "C##IGOR"."NABUGOVOR" ADD CONSTRAINT "NABUGOVOR_UGOVOR_FK" FOREIGN KEY ("IDUGO")
	  REFERENCES "C##IGOR"."UGOVOR" ("IDUGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OBUHVATAPROIZ
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."OBUHVATAPROIZ" ADD CONSTRAINT "OBUHVATAPROIZ_PRODUGOVOR_FK" FOREIGN KEY ("PRODUGOVOR_IDUGO")
	  REFERENCES "C##IGOR"."PRODUGOVOR" ("IDUGO") ENABLE;
  ALTER TABLE "C##IGOR"."OBUHVATAPROIZ" ADD CONSTRAINT "OBUHVATAPROIZ_PROIZVOD_FK" FOREIGN KEY ("PROIZVOD_IDPROIZ")
	  REFERENCES "C##IGOR"."PROIZVOD" ("IDPROIZ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OBUHVATASIR
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."OBUHVATASIR" ADD CONSTRAINT "OBUHVATASIR_NABUGOVOR_FK" FOREIGN KEY ("NABUGOVOR_IDUGO")
	  REFERENCES "C##IGOR"."NABUGOVOR" ("IDUGO") ENABLE;
  ALTER TABLE "C##IGOR"."OBUHVATASIR" ADD CONSTRAINT "OBUHVATASIR_SIROVINA_FK" FOREIGN KEY ("SIROVINA_IDSIR")
	  REFERENCES "C##IGOR"."SIROVINA" ("IDSIR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEKAR
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."PEKAR" ADD CONSTRAINT "PEKAR_ZAPOSLENI_FK" FOREIGN KEY ("IDZAP")
	  REFERENCES "C##IGOR"."ZAPOSLENI" ("IDZAP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POTPISANPUD
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."POTPISANPUD" ADD CONSTRAINT "POTPISANPUD_DISTRIBUTER_FK" FOREIGN KEY ("DISTRIBUTER_IDDIST")
	  REFERENCES "C##IGOR"."DISTRIBUTER" ("IDDIST") ENABLE;
  ALTER TABLE "C##IGOR"."POTPISANPUD" ADD CONSTRAINT "POTPISANPUD_PRODUGOVOR_FK" FOREIGN KEY ("PRODUGOVOR_IDUGO")
	  REFERENCES "C##IGOR"."PRODUGOVOR" ("IDUGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRAVI
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."PRAVI" ADD CONSTRAINT "PRAVI_PEKAR_FK" FOREIGN KEY ("PEKAR_IDZAP")
	  REFERENCES "C##IGOR"."PEKAR" ("IDZAP") ENABLE;
  ALTER TABLE "C##IGOR"."PRAVI" ADD CONSTRAINT "PRAVI_PROIZVOD_FK" FOREIGN KEY ("PROIZVOD_IDPROIZ")
	  REFERENCES "C##IGOR"."PROIZVOD" ("IDPROIZ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUGOVOR
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."PRODUGOVOR" ADD CONSTRAINT "PRODUGOVOR_PRODAVNICA_FK" FOREIGN KEY ("PRODAVNICA_IDPROD")
	  REFERENCES "C##IGOR"."PRODAVNICA" ("IDPROD") ENABLE;
  ALTER TABLE "C##IGOR"."PRODUGOVOR" ADD CONSTRAINT "PRODUGOVOR_UGOVOR_FK" FOREIGN KEY ("IDUGO")
	  REFERENCES "C##IGOR"."UGOVOR" ("IDUGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SASTAV
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."SASTAV" ADD CONSTRAINT "SASTAV_PROIZVOD_FK" FOREIGN KEY ("PROIZVOD_IDPROIZ")
	  REFERENCES "C##IGOR"."PROIZVOD" ("IDPROIZ") ENABLE;
  ALTER TABLE "C##IGOR"."SASTAV" ADD CONSTRAINT "SASTAV_SIROVINA_FK" FOREIGN KEY ("SIROVINA_IDSIR")
	  REFERENCES "C##IGOR"."SIROVINA" ("IDSIR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UGOVOR
--------------------------------------------------------

  ALTER TABLE "C##IGOR"."UGOVOR" ADD CONSTRAINT "UGOVOR_MENADZER_FK" FOREIGN KEY ("MENADZER_IDZAP")
	  REFERENCES "C##IGOR"."MENADZER" ("IDZAP") ENABLE;
